name: 打包easychat-front
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '打包类型'
        required: true
        default: 'win'
        options:
          - 'win'
          - 'mac'
          - 'linux'
      build_name:
        description: '打包名称'
        required: true
        default: 'easychat-front'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 获取源代码
        uses: actions/checkout@v4
      - name: 获取node环境
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: 安装依赖
        run: npm install
      - name: 打包
        run: npm run build:win
      - name: 上传打包文件
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.build_name }}
          path: dist/${{inputs.build_name}}-1.0.0-Setup.exe
